# Generated by Django 3.1.2 on 2020-10-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku_management', '0002_auto_20201026_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-modified_at']},
        ),
    ]
